## NUMPY, PANDAS AND MATPLOTLIB

## Numpy is a package in python for scientific computing. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [2]:
import numpy as np
a = np.array([1,2,3]) # Create a rank 1 array
print(type(a)) #Prints "<class 'numpy.ndarray'>"
print(a.shape) #Print"(3,)"

print(a[0], a[1],a[2]) #Print"123"

a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]]) # Create a rank 2 array
print(b.shape)
print(b[0,0], b[0,1],b[1,0]) # prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [3]:
import numpy as np

a = np.zeros((2,2)) # Create an array of all zeros

print(a) 

[[0. 0.]
 [0. 0.]]


In [5]:
b = np.ones((3,3)) # Create an array of all ones
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2) # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [10]:
e= np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.9241767  0.03729499]
 [0.56257092 0.83543305]]


## Numpy offers several ways to index into arrays:

## Slicing: Similar to python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [12]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
b = a[:2,1:3] 

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape(2,2):

print(a[0,1])
print(b)
b[0,0] =77
print(a[0,1])

77
[[77  3]
 [ 6  7]]
77
