In [51]:
import numpy as np

a = np.array(([1,2,3,4,5],[6,7,8,9,10]))

b = np.max(a, axis = 1).sum()

In [2]:
b

15

In [8]:
import numpy as np

#List is slow
#Numpy very fast, fixed

In [4]:
a = [1,3,5]
b = [1,2,3]

a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [13]:
a = np.array([1,3,5], dtype ='int16')
b= np.array([1,2,3])

a*b

array([ 1,  6, 15])

In [6]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
#Get Dimension
a.ndim

1

In [11]:
#Get shape
b.shape

(2, 3)

In [14]:
#Get Type
a.dtype

dtype('int16')

In [15]:
#Get size
a.itemsize

2

In [16]:
a.size

3

In [17]:
a.itemsize*a.size

6

In [18]:
#Get total size

a.nbytes

6

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [16]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
a[1,5]

13

In [18]:
#Get a specific element

a[1,5]

13

In [19]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-2:2]

array([2, 4])

In [21]:

a[0,1:-1:2]

array([2, 4, 6])

In [22]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
a[:,2]=[1,4]

In [30]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  4 11 12 20 14]]


In [43]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
#replace

b[:,1,:]=[[9,9],[8,8]]

In [47]:
b

array([[[9, 9],
        [9, 9]],

       [[8, 8],
        [8, 8]]])

In [59]:
# All 0s matrix
np.zeros((1,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [60]:
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [62]:
np.full_like(a.shape,4)

array([4, 4])

In [65]:
np.random.rand(4,2)

array([[0.88534978, 0.12597604],
       [0.69850584, 0.95233378],
       [0.59474831, 0.21715722],
       [0.04844184, 0.99708165]])

In [66]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
arr =  np.array([[1,2,3]])
r1= np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
a = np.array([1,2,3])

In [69]:
print(a**2)

[1 4 9]


In [70]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# Linear Algebra

In [71]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [73]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [74]:
#Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [75]:
###Statistics

In [76]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.max(stats)

6

In [78]:
np.min(stats)

1

In [82]:
np.min(stats, axis = 1)

array([1, 4])

Reorganising Arrays

In [86]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [88]:
print(before.shape)

(2, 4)


In [89]:
after=before.reshape((4,2))

In [90]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [91]:
#Horizontal stack

h1 = np.ones((2,4))
h2 =np.zeros((2,2))

In [92]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [93]:
#Boolean Indexing and Advanced Indexing

In [94]:
a = np.array([2,5,9])

In [95]:
a> 5

array([False, False,  True])