# A Little about Matrix

In [26]:
import numpy as np
M = np.array([[1,4,8],[9,1,0],[8,7,1]])


In [27]:
M

array([[1, 4, 8],
       [9, 1, 0],
       [8, 7, 1]])

In [29]:
# Transpose
print(M.T)

[[1 9 8]
 [4 1 7]
 [8 0 1]]


In [30]:
#Inverse
Minv = np.linalg.inv(M)

In [31]:
Minv

array([[ 0.00246914,  0.12839506, -0.01975309],
       [-0.02222222, -0.15555556,  0.17777778],
       [ 0.13580247,  0.0617284 , -0.08641975]])